### ISSUE TITLE
Stats pulldowns are empty

### ISSUE THREAD

**Issue by dbaston** [JakubCha/exactextract_qgis#26]
Hi, I was trying to test this out and I'm finding that the menus to select a stat are unpopulated. I've tried installing both from git and from the plugin repository.

![image](https://github.com/user-attachments/assets/80b9b68f-bbe5-4464-a9db-20056c7c3575)

Any ideas?

QGIS version | 3.38.0-Grenoble | 
QGIS code revision | 37aa6188bc3
Qt version | 5.15.3
Python version | 3.10.12

**Comment by JakubCha** [comment]
Hi. What's the OS? 
When you click the right arrow in right to the `Aggregates` combobox does it dropdown to anything or show only some empty space like you would have with `Weights` dropdown by default?

**Comment by dbaston** [comment]
Pop OS 22.04 (Ubuntu derivative)

Clicking the right arrow has no effect whatsoever.

**Comment by JakubCha** [comment]
I believe it's a qgis/OS-related bug with `QgsCheckableComboBox`, but I will try replicating it on some fresh Pop OS instance. Currently, I only have access to Windows GUI.

**Comment by dbaston** [comment]
Just installed on a Windows laptop and the pulldowns seem to work fine.

It's been a while since I've worked on a QGIS plugin. Is there a way I should be able to see exceptions raised by the Python code?

**Comment by JakubCha** [comment]
Sure, right-click anywhere on panels and tick `Log Messages Panel`. It will show any python related warnings and errors. Below is a gif on how to do that.
![Animation](https://github.com/user-attachments/assets/fe423abf-4201-4197-880f-3529f360e9b3)

**Comment by JakubCha** [comment]
I can confirm that the `QgsCheckableComboBox` widgets are empty in fresh Pop OS. When I removed the `PythonHighlighter` from the `CodeEditor` widget Python didn't output any warnings or errors so I believe it's not a plugin error.
I don't know any good alternative for the `QgsCheckableComboBox` widget right now.

**Comment by JakubCha** [comment]
@dbaston Can you try with the code from #27 ? I've tested it with Pop OS instance and it shows statistics now but your confirmation that it works fine would be great.

**Comment by dbaston** [comment]
@JakubCha thanks, that fixes this issue for me!

**Comment by JakubCha** [comment]
It's fixed with the new merge. Thank you for reporting @dbaston !
