### ISSUE TITLE
Refactor plugin code to QGISFeatureSource exactextract API change

### ISSUE THREAD

**Issue by JakubCha** [JakubCha/exactextract_qgis#4]
It seems that QGIS returns a query string to the database. The geometry column should be adjusted so the layer can be properly read.

**Comment by JakubCha** [comment]
Usage of QGIS connection info would require QGIS user to save username/password as plain text or authentication config during database connection. I shouldn't force this upon users.
More about this [here](https://gis.stackexchange.com/questions/318635/getting-active-postgresql-connection-username-when-stored-through-authentication ):

**Comment by dbaston** [comment]
It might be helpful to write adapters so that `exactextract` can iterate directly over the features in a QGIS layer, e.g.

```
from exactextract.feature import Feature, FeatureSource

class QGISFeature(Feature):

    def __init__(self, f=None):
        super().__init__()
        self.feature = f 

    def geometry(self):
        return bytes(self.feature.geometry().asWkb())

    def get(self, name):
        return self.feature[name]

    def fields(self):
        return [field.name() for field in self.feature.fields()]

class QGISFeatureSource(FeatureSource):

    def __init__(self, src):
        super().__init__()
        self.src = src

    def __iter__(self):
        for f in self.src.getFeatures():
            yield QGISFeature(f)

    def srs_wkt(self):
        return self.src.sourceCrs().toWkt()
```

These adapters would either need to live in the `exactextract` library or the library would need to provide some way to register externally-defined adapters.

Similarly, it would be possible to write outputs to a new QGIS layer if desired.

**Comment by JakubCha** [comment]
Thank you Dan for your comment!

Yeah, as you mentioned, the only possibility to add true QGIS compatibility with `exactextract` is to write an adapter. That's also one of the features to be implemented that I had in plans.
I am currently exploring possibilities of `QgsVectorLayer` to be directly used in adapter. It seems that it provides an iterator (`QgsVectorLayer.getFeatures()`) and WKB conversion (`QgsFeature.geometry().asWkb()`) so it _should_ be possible and efficient.

I will try to add it to `exactextract`.

**Comment by dbaston** [comment]
Here, give this PR a try: https://github.com/isciences/exactextract/pull/85

**Comment by JakubCha** [comment]
Did some quick, rough tests in debugging mode with code:
```python
result_stats = exact_extract(vec=self.mVectorLayerComboBox.currentLayer(), rast=self.mRasterLayerComboBox.currentLayer().dataProvider().dataSourceUri(), 
ops=self.mAggregatesComboBox.checkedItems(), output="pandas")
```
and it returns statistics without raising any exceptions so it's a good start.
I will test further this API change and modify my plugin code accordingly.

Thank you Dan for this addition to `exactextract`!

**Comment by JakubCha** [comment]
#5
